
version: '3'

services:
  # mongodb:
  #   image: mongo
  #   container_name: mongodb
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb_data:/data/db
      
    

  blockchain_server:
    build:
      context: ./blockchainserver
    container_name: blockchain_server
    ports:
      - "5000:5000"
    networks:
      - app_network

  server:
    build:
      context: ./server
    container_name: server
    ports:
      - "8000:8000"
    # depends_on:
    #   - mongodb
    networks:
      - app_network

  client:
    build:
      context: ./client
    container_name: client
    ports:
      - "3000:3000"
    depends_on:
      - server
      - blockchain_server
    networks:
      - app_network

networks:
  app_network:
    driver: bridge


  
  
